client:
  nodelay: # bool, whether or not to set tcp_nodelay option
server:
  nodelay: # bool, whether or not to set tcp_nodelay option
jobs:
  - name: # any parseable string
    type: # string, one of: rpc
    verb: # string, one of: echo
    parallelism: # number of verbs to send simultaneously
    shares: # sched group shares (100 by default)
