name: Test

permissions:
  contents: read

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}

jobs:
  test:
    name: "Tests (${{ matrix.compiler }}, C++${{ matrix.standard}}, ${{ matrix.mode }}, ${{ matrix.enables }})"
    uses: ./.github/workflows/test.yaml
    strategy:
      fail-fast: false
      matrix:
        # only the compilers supported by setup-cpp
        compiler: [clang++-18, gcc-13]
        standard: [20, 23]
        mode: [dev, debug, release]
        include:
          - compiler: clang++-18
            standard: 20
            mode: dev
          - compiler: clang++-18
            standard: 20
            mode: debug
          - compiler: clang++-18
            standard: 20
            mode: release
          - compiler: clang++-18
            standard: 23
            mode: dev
          - compiler: clang++-18
            standard: 23
            mode: debug
          - compiler: clang++-18
            standard: 23
            mode: release
          - compiler: gcc-13
            standard: 20
            mode: dev
          - compiler: gcc-13
            standard: 20
            mode: debug
          - compiler: gcc-13
            standard: 20
            mode: release
          - compiler: gcc-13
            standard: 23
            mode: dev
          - compiler: gcc-13
            standard: 23
            mode: debug
          - compiler: gcc-13
            standard: 23
            mode: release
          - compiler: clang++-18
            standard: 23
            mode: release
            options: --cook dpdk --dpdk-machine haswell
            enables: --enable-dpdk
          - compiler: clang++-18
            standard: 23
            mode: debug
            enables: --enable-cxx-modules
    with:
      compiler: ${{ matrix.compiler }}
      standard: ${{ matrix.standard }}
      mode: ${{ matrix.mode }}
      enables: ${{ matrix.enables }}
      options: ${{ matrix.options }}
